# Override values for HyperShift 
global:
  useExternalSecrets: true
  s3:
    createBucket: false
    region: ap-southeast-1
    bucketName:
    additionalTags:

  buildconfig:
    git:
      uri:
      ref:
