kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cte-csi-node-ac
  namespace: {{ .Values.cte.cteNS }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "watch", "get"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "list", "delete", "get", "patch"]

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "update", "delete"]

  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "patch"]

  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "patch"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes", "storageclasses"]
    verbs: ["get", "list", "watch", "patch"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "patch"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]

  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["cte-csi-scc"]
    verbs: ["use"]
