kind: Subscription
apiVersion: operators.coreos.com/v1alpha1
metadata:
  name: ctek8soperator-sub
  namespace: {{ .Values.cte.operatorDeployNS }}
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cte-k8s-operator
  # Coded for OCP ONLY
  source: certified-operators
  sourceNamespace: openshift-marketplace
