{{- if .Values.global.useExternalSecrets }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: eso-hypershift-pull-secret
  namespace: cluster
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: hypershift-pull-secret
    template:
      type: Opaque
  - extract:
      key: {{ .Values.ocpPullCreds.key }}
{{- end }}