
# apiVersion: multicluster.openshift.io/v1
# kind: MultiClusterEngine
# metadata:
#   name: multiclusterengine
# spec:
#   availabilityConfig: Basic
#   targetNamespace: multicluster-engine
#Test whether required. This should now be turned on by default.
#   overrides:
#     components:
#     - enabled: true
#       name: local-cluster
#     - enabled: true
#       name: assisted-service
#     - enabled: true
#       name: cluster-lifecycle
#     - enabled: true
#       name: cluster-manager
#     - enabled: true
#       name: discovery
#     - enabled: true
#       name: hive
#     - enabled: true
#       name: server-foundation
#     - enabled: true
#       name: cluster-proxy-addon
#     - enabled: true
#       name: hypershift-local-hosting
#     - enabled: true
#       name: managedserviceaccount-preview
#     - enabled: true
#       name: hypershift-preview
#     - enabled: true
#       name: console-mce
#   targetNamespace: multicluster-engine
#   tolerations:
#   - effect: NoSchedule
#     key: node-role.kubernetes.io/infra
#     operator: Exists
