apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: golang-external-secrets
spec:
  provider:
    vault:
      server: https://vault-vault.{{ .Values.global.hubClusterDomain }}
      path: secret
      # Version of KV backend
      version: v2
{{- if .Values.golangExternalSecrets.caProvider.enabled }}
{{ if .Values.clusterGroup.isHubCluster }}
      caProvider:
        type: {{ .Values.golangExternalSecrets.caProvider.vaultHostCluster.type }}
        name: {{ .Values.golangExternalSecrets.caProvider.vaultHostCluster.name }}
        key: {{ .Values.golangExternalSecrets.caProvider.vaultHostCluster.key }}
        namespace: {{ .Values.golangExternalSecrets.caProvider.vaultHostCluster.namespace }}
{{ else }}
      caProvider:
        type: {{ .Values.golangExternalSecrets.caProvider.vaultClientCluster.type }}
        name: {{ .Values.golangExternalSecrets.caProvider.vaultClientCluster.name }}
        key: {{ .Values.golangExternalSecrets.caProvider.vaultClientCluster.key }}
        namespace: {{ .Values.golangExternalSecrets.caProvider.vaultClientCluster.namespace }}
{{ end }}
{{- end }}
      auth:
        kubernetes:
{{ if .Values.clusterGroup.isHubCluster }}
          mountPath: {{ .Values.mountPath }}
          role: {{ .Values.mountRole }}
{{ else }}
          mountPath: {{ $.Values.global.clusterDomain }}
          role: {{ $.Values.global.clusterDomain }}-role
{{ end }}
          secretRef:
            name: golang-external-secrets
            namespace: golang-external-secrets
            key: "token"
