global:
  pattern: encrypted-control-planes

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  ecp:
    # leave blank for an internal deployment or define a full URL.
    aapURL: ''

    # IP for a CTM server. Assumes 
    cipherTrustIP: ''

    # Whether or not to deploy OCP-V on a BM instance for AWS.
    # Assumes ROSA is not being used for the deployment.
    cnv: false
    cnvAWSBareMetal: false

    # Base storage class to use. 
    storageClass: gp3-csi

main:
  clusterGroupName: hub

  multiSourceConfig:
    enabled: true
