global:
  pattern: encrypted-control-planes

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  ecp:
    # leave blank for an internal deployment or define a full URL.
    aapURL: ''


    ctm:
      onCluster: false
      ip: '52.62.109.252'
    # IP for a CTM server. Assumes the CTM server is not on cluster.


    # Whether or not to deploy OCP-V on a BM instance for AWS.
    # Assumes ROSA is not being used for the deployment.
    cnv:
      enabled: true
      nestedVirt: false
      bm: true
      AWSBareMetal:
        enabled: false
        nodeFlavour: m5.metal
        nodeCount: 1
        region: ''
        availabilityZone: ''
    # Base storage class to use. 
    storageClass: ocs-storagecluster-ceph-rbd
    storageClassBind: Immediate

    APIPublishingStrategy: NodePort
    baseDomain: 2g96t.sandbox3015.opentlc.com
    NodePortAddress: 10.0.0.1

main:
  clusterGroupName: hub

  multiSourceConfig:
    enabled: true
