global:
  pattern: encrypted-control-planes

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

main:
  clusterGroupName: local-cluster

  multiSourceConfig:
    enabled: true
