secretStore:
  name: vault-backend
  kind: ClusterSecretStore

pullSecret:
  key: secret/data/global/cteDockerIO

global:

  # Provision External Secret resources: default true
  useExternalSecrets: true
cteReg:
  key: secret/data/global/cteregistrationtoken
