---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: ansible-token-eso
  namespace: ansible-automation-platform
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: ansible-token
  dataFrom:
  - extract:
      key: {{ .Values.ansibleToken.key }}
