---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: rhsm
  namespace: ansible-automation-platform
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: rhsm
  dataFrom:
  - extract:
      key: {{ .Values.rhsm.key }}
