# ---
# apiVersion: "tower.ansible.com/v1alpha1"
# kind: AnsibleCredential
# metadata:
#   name: test-ac
#   namespace: ansible-automation-platform
# spec:
#   connection_secret: ansible-token
#   description: "Test credential"
#   ssh_secret: test
#   type:
#   name: 
#   organization: 
