{{- if .Values.global.ecp.ctm.onCluster -}}
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: ciphertrust-vm
  name: ciphertrust-vm
  namespace: cte-vm
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: ciphertrust-dv 
    spec:
      storage:
        resources:
          requests:
            storage: 10Gi
      source:
        http:
          url: "https://www.ciphertrust.io/files/Virtual_CipherTrust_Manager_OpenStack.qcow2" 
          # secretRef: data-source-secret 
          # certConfigMap: tls-certs 
    status: {}
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vm: ciphertrust-vm
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk2
        machine:
          type: ""
        resources:
          requests:
            memory: 1.5Gi
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: ciphertrust-dv
        name: datavolumedisk2
{{- end -}}