apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  creationTimestamp: null
  name: 'np-{{ .Release.Namespace }}-{{ .Release.Name }}'
  namespace: cluster
spec:
  arch: amd64
  clusterName: '{{ .Release.Name }}'
  management:
    autoRepair: false
    upgradeType: Replace
  nodeDrainTimeout: 0s
  platform:
    kubevirt:
      compute:
        cores: 2
        memory: 6Gi
      rootVolume:
        persistent:
          size: 32Gi
{{ if .Values.global.ecp.encryptedDataPlane }}
          storageClass: cte-sc-{{ .Release.Namespace }}-{{ .Release.Name }}
{{ else }}
          storageClass: {{ .Values.unencryptedStorageClass }}
{{ end}}
        type: Persistent
    type: KubeVirt
  release:
    image: quay.io/openshift-release-dev/ocp-release:{{ .Values.ocpVersion }}-x86_64
  replicas: 1
status:
  replicas: 0
---
