{{- if .Values.global.useExternalSecrets }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: htpass-user-secrets
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: htpass-secret
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.htpasswordCreds.key }}
{{- end }}
