# Default values for AWS S3 Controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  ecp:
    cnv:
      enabled: false
      nestedVirt: false
      AWSBareMetal:
        enabled: false
        nodeFlavour: m5.metal
        nodeCount: 1
        region: ''
        availabilityZone: ''
