{{- range .Values.templates }}
apiVersion: clustertemplate.openshift.io/v1alpha1
kind: ClusterTemplate
metadata:
  name: hypershift-{{ .name }}
spec:
  clusterDefinition: cluster-definition-app-{{ .name }}
{{- if .bootstrap }}
  clusterSetup:
    - cluster-setup-definition-app-{{ .name }}
{{- end }}
  cost: 1

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-definition-app-{{ .name }}
  namespace: cluster-aas-operator # in the operator namespace where the operator can orchestrate it
spec:
  generators:
  - {}
  template:
    metadata: {}
    spec:
      destination:
        namespace: {{ $.Values.namespace }}
        server: 'https://kubernetes.default.svc'
      project: {{ $.Values.namespace }}
      source:
        path: charts/cluster/definition/{{ .defintion }}
        repoURL: {{ $.Values.global.repoURL }}
        targetRevision: {{ $.Values.global.targetRevision }}
        helm:
          parameters:
  {{- if $.Values.global.useExternalSecrets }}
          - name: secret-store-name 
            value: {{ $.Values.secretStore.name }}
          - name: secret-store-kind
            value: {{ $.Values.secretStore.kind }}
  {{- end }}
          - name: cpPolicy
            value: {{ .cpPolicy }}
          - name: nodepoolReplicas
            value: "{{ toString .nodes }}"

          - name: APIPublishingStrategy
            value: {{ $.Values.APIPublishingStrategy }}
          - name: baseDomain # Fixme should be different
            value: {{ $.Values.baseDomain }}
          - name: NodePortAddress
            value: {{ $.Values.NodePortAddress }}
      syncPolicy:
        automated: {}

---
{{- if .bootstrap }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-setup-definition-app-{{ .name }}
  namespace: cluster-aas-operator
spec:
  generators:
  - {}
  template:
    metadata: {}
    spec:
      destination:
        namespace: {{ $.Values.namespace }}
        server: 'https://kubernetes.default.svc'
      project: {{ $.Values.namespace }}
      source:
        path: common/install
        repoURL: {{ $.Values.global.repoURL }}
        targetRevision: main
      syncPolicy:
        automated: {}
{{- end }}
---
{{- end }}
