{{- if .Values.global.useExternalSecrets }}
# this is a hack for now.
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: eso-pull-secret
  namespace: cluster #FIXME pass across
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: pull-secret
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.pullSecret.key }}
{{- end }}
