apiVersion: v1
kind: ConfigMap
metadata:
  name: ack-s3-user-config
  namespace: ack-system
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
data:
{{- range $k, $v := .Values.ackS3 }}
  {{ $k | upper }}: {{ $v | quote }}
{{- end }}
  AWS_REGION: {{ $.Values.global.s3.region | quote}}
  ACK_WATCH_NAMESPACE: ""
  AWS_ENDPOINT_URL: ""
  LEADER_ELECTION_NAMESPACE: ""
