{{- if .Values.global.useExternalSecrets }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: ack-eso-s3-user-secrets
  namespace: ack-system
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: ack-s3-user-secrets
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.ackCredentials.key }}
{{- end }}
