# Default values for hypershift.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
clusterGroup:
  isHubCluster: true

# Reference the Hashicorp Vault backend for ESO
secretStore:
  name: vault-backend
  kind: ClusterSecretStore

# Secret provisioned for the HyperShift installation 
awsCredentials:
  key: secret/data/hub/awsCreds

# Begin global parameters
global:
  # Provision External Secret resources: default true
  useExternalSecrets: true

# End global parameters
