apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cte-sc-{{ .Release.Namespace }}-{{ .Release.Name }}
provisioner: csi.cte.cpl.thalesgroup.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:

  # Domain name or IP address of the CipherTrust Manager (Required)
  key_manager_addr: 13.251.63.29

  # Name of the CipherTrust Manager K8s Storage Group. (Required)
  k8_storage_group: sg-{{ .Release.Namespace }}-{{ .Release.Name }}

  # Kubernetes Secret with CM registration token (Required)
  registration_token_secret: cte-reg-token

  source_storage_class: {{ .Values.providerStorageClass }}

  default_policy: Policy-{{ .Release.Namespace }}-{{ .Release.Name }}
  # Time in minutes to wait before unregistering from the CipherTrust Manager
  # once all of the volumes have been unguarded. Parameter must be added as a string
  # integer value. Default is 10 minutes. (Optional)

  allow_source_pvc_delete: "true"
  registration_period: "10"
