---
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  creationTimestamp: null
  name: kubevirt2
  namespace: local-cluster
spec:
  clusterName: kubevirt2
  management:
    autoRepair: false
    upgradeType: Replace
  nodeDrainTimeout: 0s
  platform:
    type: None
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.13.4-x86_64
  replicas: 1
status:
  replicas: 0
---