# WARNING!
# WARNING!
# This is not directly orchestrated via the validated patterns operator. 
# As a result it does not direclty inherit from values-global or similar.
# Parameters should be 'explicitly' passed via helm parameters via 


## Keep this file flat due to parameter passing elsehwere

unencryptedStorageClass: ''
storageClassBind: ''
encryptDataPlane: false
ctmIP: ''
ocpVersion: 4.14.9
cpPolicy: ''

cteRegKey: secret/data/global/cteregistrationtoken


# FIXME: This is effectively hardcoded here
secretStore:
  name: vault-backend
  kind: ClusterSecretStore
