---
apiVersion: "tower.ansible.com/v1alpha1"
kind: AnsibleProject
metadata:
  name: ansible-project
  namespace: {{ .Values.aapNamespace }}
spec:
  branch: {{ .Values.global.targetRevision }}
  connection_secret: {{ .Values.connectionSecret }}
  description: "Ansible project to wrap jobs interacting with the ciphetrust manager"
  name: cte-automation-project
  organization: {{ .Values.organisation }}
  repo: {{ .Values.global.repoURL }}
  scm_type: git