---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: ansible-token-es
  namespace: cte
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: cte-imperative-ss
    kind: SecretStore
  target:
    name: ansible-token
  dataFrom:
    key: controller-login-token