---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: ansible-token-es
  namespace: cte
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: imperative-ss
    kind: ClusterSecretStore
  target:
    name: ansible-token
    template:
      mergePolicy: Merge
      type: Opaque
      data:
        host: https://controller-ansible-automation-platform.{{ .Values.global.hubClusterDomain }}
  data:
  
  - secretKey: token
    remoteRef:
      key: controller-login-token
      property: token