---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: ansible-token-es
  namespace: {{ .Values.aapNamespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: imperative-ss
    kind: ClusterSecretStore
  target:
    name: {{ .Values.connectionSecret }}
    template:
      mergePolicy: Merge
      type: Opaque
      data:
        host: {{ default (printf "https://controller-ansible-automation-platform.%s" .Values.global.hubClusterDomain) .Values.global.ecp.aapURL | ne "" }}
  data:
  - secretKey: token
    remoteRef:
      key: controller-login-token
      property: token