---
apiVersion: "tower.ansible.com/v1alpha1"
kind: JobTemplate
metadata:
  name: cte-key-template
  namespace: {{ .Values.aapNamespace }}
spec:
  connection_secret: {{ .Values.connectionSecret }}
  inventory: cte-inventory
  description: inventory job template
  name: cte-key-job
  project: cte-automation-project
  playbook: 'ansible/cte-job.yaml'
  organization: {{ .Values.organisation }}
  credentials:
    - ctm-password-as-network

  extra_vars:
    clusterID: 'placeholder'
