---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: ctm-password-as-network
  namespace: {{ .Values.aapNamespace }}
spec:
  name: ctm-password-as-network
  organization: {{ .Values.organisation }}
  connection_secret: {{ .Values.connectionSecret }}
  description: "ctm password as a network credential"
  type: "Network"
  username_secret: ctm-password
  password_secret: ctm-password
  runner_pull_policy: IfNotPresent
