# apiVersion: "external-secrets.io/v1beta1"
# kind: ExternalSecret
# metadata:
#   name: ctm-password-eso
#   namespace: {{ .Values.aapNamespace }}
# spec:
#   refreshInterval: 15s
#   secretStoreRef:
#     name: vault-backend
#     kind: ClusterSecretStore
#   target:
#     name: ctm-token
#     template:
#       engineVersion: v2
#       data:
#         username: placeholder # required for current types available on the ansible side
#         password: "{{ `{{ .password }}` }}" # escaped for helm use.
#   data:
#   - secretKey: password
#     remoteRef:
#       key: secret/data/global/cteregistrationtoken
#       property: registration_token
# Version above was wrong. Using admin password not registration_token. Useful to underestand
---

apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: ctm-password-eso
  namespace: {{ .Values.aapNamespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target: ctm-password
  dataFrom:
    - extract:
        key: 'secret/data/global/cteAdminLogin'