apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: ctm-password-eso
  namespace: {{ .Values.aapNamespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ctm-password
  dataFrom:
    - extract:
        key: 'secret/data/global/cteAdminLogin'