apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: ctm-token-eso
  namespace: {{ .Values.aapNamespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ctm-token
    template:
      engineVersion: v2
      data:
        username: admin     # If you are using plain manifests or gitops tools
        password: "{{ `{{ .password }}` }}"      
  data:
  - secretKey: password
    remoteRef:
      key: secret/data/global/cteregistrationtoken
      property: registration_token