# Fake secret
# this is used for testing secret propagation
---
apiVersion: v1
kind: Secret
metadata:
  name: fake-secret
  namespace: {{ .Values.aapNamespace }}
type: Opaque
data:
  username: ZmFrZQo=
  password: ZmFrZQo=