---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: cte-imperative-ss
  namespace: cte
spec:
  provider:
    kubernetes:
      server:
        url: https://kubernetes.default.svc
      auth:
        serviceAccount: eso-sa
      namespace: imperative