apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: imperative
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader
subjects:
- kind: ServiceAccount
  name: eso-sa
  namespace: cte
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader-binding
  namespace: openshift-kube-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: config-reader
subjects:
- kind: ServiceAccount
  name: eso-sa
  namespace: cte
- kind: ServiceAccount
  name: default
  namespace: cte
# - kind: ServiceAccount
#   name: golang-external-secrets
#   namespace: golang-external-secrets
---
