# This is a test job.
# Unfortunately 
---
apiVersion: "tower.ansible.com/v1alpha1"
kind: AnsibleJob # note must have a template
metadata:
  name: ansible-job-test-secrets-three
  namespace: {{ .Values.aapNamespace }}
spec:
  connection_secret: ansible-token
  name: ansible-test-job
  job_template_name: cte-key-job # reference ansible job not the k8s definition
  extra_vars:
    new_cluster_id: test-cluster
    
