{{- if .Values.global.useExternalSecrets }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: cte-docker-pull-secret
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: cte-csi-secret
    namespace: openshift-operators
    template:
      type: kubernetes.io/dockerconfigjson
  dataFrom:
  - extract:
      key: {{ .Values.pullSecret.key }}
{{- end }}
