{{- if .Values.global.useExternalSecrets }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: eso-cte-reg-token
  namespace: openshift-operators
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: cte-reg-token
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.cteReg.key }}
{{- end }}