apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints 
metadata:
  name: cte-csi-scc
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowedCapabilities:
  - SYS_ADMIN
allowHostPID: true
volumes:
  - emptyDir
  - hostPath
  - projected
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny 
fsGroup:
  type: RunAsAny