apiVersion: v1
kind: ConfigMap
metadata:
    name: aap-configmap
    namespace: ansible-automation-platform
data:
    aapURL: {{ .Values.global.aapURL }}
    project_repo: "{{ $.Values.global.repoURL }}"
    project_branch: "{{ $.Values.global.targetRevision }}"