#!/usr/bin/env ansible-playbook
---
- name: Retrieve Credentials from Kubernetes for use in AAP
  become: false
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
  tasks:
    - name: Retrieve manifest file
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: ansible-automation-platform
        name: aap-manifest
      register: manifest_secret
      until: manifest_secret.resources | length == 1
      retries: 20
      delay: 5

    - name: Set manifest fact
      ansible.builtin.set_fact:
        manifest_file: "{{ manifest_secret.resources[0].data.b64content | b64decode | b64decode }}"

    - name: Write temp manifest file
      ansible.builtin.tempfile:
        state: file
        suffix: .zip
      register: manifest_file_tmp

    - name: Set manifest_file_ref fact
      ansible.builtin.set_fact:
        manifest_file_ref: "{{ manifest_file_tmp.path }}"

    - name: Copy manifest contents to tmpfile
      ansible.builtin.copy:
        content: "{{ manifest_file }}"
        dest: "{{ manifest_file_ref }}"
        mode: "0644"

    - name: Retrieve kubeconfig secret
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: openshift-kube-apiserver
        name: node-kubeconfigs
      register: node_kubeconfigs
      until: node_kubeconfigs.resources | length == 1
      retries: 20
      delay: 5

    # - name: Retrieve rhsm secret
    #   kubernetes.core.k8s_info:
    #     kind: Secret
    #     namespace: ansible-automation-platform
    #     name: rhsm
    #   register: rhsm_secret
    #   until: rhsm_secret.resources | length == 1
    #   retries: 20
    #   delay: 5

    # - name: Retrieve kiosk-ssh secret
    #   kubernetes.core.k8s_info:
    #     kind: Secret
    #     namespace: ansible-automation-platform
    #     name: kiosk-ssh
    #   register: kiosk_ssh_secret
    #   until: kiosk_ssh_secret.resources | length == 1
    #   retries: 20
    #   delay: 5

    # - name: Retrieve kiosk-extra secret
    #   kubernetes.core.k8s_info:
    #     kind: Secret
    #     namespace: ansible-automation-platform
    #     name: kiosk-extra
    #   register: kiosk_extra_secret
    #   until: kiosk_extra_secret.resources | length == 1
    #   retries: 20
    #   delay: 5

    - name: Set secrets for use in load controller playbook
      ansible.builtin.set_fact:
        secrets:
          manifest_file_ref: "{{ manifest_file_ref }}"
          kubeconfig: "{{ node_kubeconfigs.resources[0].data['lb-ext.kubeconfig'] | b64decode }}"
          # rhsm:
          #   username: "{{ rhsm_secret.resources[0].data.username | b64decode }}"
          #   password: "{{ rhsm_secret.resources[0].data.password | b64decode }}"
          # kiosk-extra:
          #   container_extra_params: "{{ kiosk_extra_secret.resources[0].data.container_extra_params | b64decode }}"
          # kiosk-ssh:
          #   username: "{{ kiosk_ssh_secret.resources[0].data.username | b64decode }}"
          #   privatekey: "{{ kiosk_ssh_secret.resources[0].data.privatekey | b64decode }}"
          #   publickey: "{{ kiosk_ssh_secret.resources[0].data.publickey | b64decode }}"

    # - debug:
    #    var: secrets
