- hosts: localhost
  connection: local
  vars:
    message: "Hello, Ansible!"
  tasks:
  - name: Echo the input variable
    debug:
      msg: {{ lookup('ansible.builtin.env', 'ANSIBLE_NET_PASSWORD')|default('nobody', True) }}
