apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: imperative-ss
  namespace: golang-external-secrets # bundle together
spec:

  provider:
    kubernetes:
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount: 
          name: golang-external-secrets
          namespace: golang-external-secrets
      remoteNamespace: imperative