
namespace: cluster
project: cluster
global:
  useExternalSecrets: true
  targetRevision: main
  repoURL: 'https://github.com/butler54/encrypted-control-planes.git'
templates:
- name: control-plane-only
  definition: 'bare-cp'
  cpPolicy: SingleReplica
  nodes: "0"
  bootstrap: false

- name: control-plane-only-ha
  definition: 'bare-cp'
  cpPolicy: HighlyAvailable
  nodes: "0"
  bootstrap: false

sshkey:
  key: secret/data/global/clusterssh

APIPublishingStrategy: NodePort
baseDomain: sandbox949.opentlc.com
NodePortAddress: 10.0.0.1
secretStore:
  name: vault-backend
  kind: ClusterSecretStore


# {{ if .Values.foo.bar }}
# {{ .Values.foo.bar }}
# {{ end }}

# - name: aws-single-node
#   definition: 'aws'
#   bootstrap: 'kubelet'
#   cp-replicas: 1
#   nodes: 1

# - name: global.repoURL
#   value: 'https://github.com/butler54/encrypted-control-planes.git'
# - name: global.targetRevision
#   value: main
# - name: global.hubClusterDomain
#   value: apps.cluster-fdjpc.fdjpc.sandbox949.opentlc.com
# - name: global.localClusterDomain
#   value: apps.cluster-fdjpc.fdjpc.sandbox949.opentlc.com
# - name: global.clusterDomain
#   value: cluster-fdjpc.fdjpc.sandbox949.opentlc.com
