
namespace: cluster
project: cluster

templates:
- name: control-plane-only
  definition: 'kubevirt'
  cpPolicy: SingleReplica
  nodes: "0"
  bootstrap: false


- name: control-plane-only-ha
  definition: 'kubevirt'
  cpPolicy: HighlyAvailable
  nodes: "0"
  bootstrap: false

- name: kubevirt-single-node
  definition: 'kubevirt'
  cpPolicy: SingleReplica
  nodes: "1"
  bootstrap: false

- name: kubevirt-three-node
  definition: 'kubevirt'
  cpPolicy: HighlyAvailable
  nodes: "3"
  bootstrap: false

- name: aws-single-node
  definition: 'aws'
  cpPolicy: SingleReplica
  nodes: "1"
  bootstrap: false

- name: aws-three-node
  definition: 'aws'
  cpPolicy: SingleReplica
  nodes: "3"
  bootstrap: false

sshkey:
  key: secret/data/global/clusterssh

pullSecret:
  key: secret/data/global/ocpPull

global:
  useExternalSecrets: true
  targetRevision: main
  repoURL: 'https://github.com/butler54/encrypted-control-planes.git'
  ecp:
    # This is used for AWS
    APIPublishingStrategy: NodePort
    baseDomain: 2g96t.sandbox3015.opentlc.com
    NodePortAddress: 10.0.0.1
    # 
    storageClass: ''
    storageClassBind: Immediate
    encryptedDataPlane: false
    ctm:
      ip: ''

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

# {{ if .Values.foo.bar }}
# {{ .Values.foo.bar }}
# {{ end }}

# - name: aws-single-node
#   definition: 'aws'
#   bootstrap: 'kubelet'
#   cp-replicas: 1
#   nodes: 1

# - name: global.repoURL
#   value: 'https://github.com/butler54/encrypted-control-planes.git'
# - name: global.targetRevision
#   value: main
# - name: global.hubClusterDomain
#   value: apps.cluster-fdjpc.fdjpc.sandbox949.opentlc.com
# - name: global.localClusterDomain
#   value: apps.cluster-fdjpc.fdjpc.sandbox949.opentlc.com
# - name: global.clusterDomain
#   value: cluster-fdjpc.fdjpc.sandbox949.opentlc.com
